# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: omarci1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setting initial vars
        run: |
           git config --global user.name "Omar Hamad"
           git config --global user.email "omartldr@gmail.com"
           git config --global color.ui false

      - name: Cloning dependencies
        run: |
           git clone --depth=1 https://github.com/etahamad/kernel_xiaomi_lavender kernel
           git clone --depth=1 https://github.com/sohamxda7/llvm-stable  kernel/clang
           git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b gcc64 kernel/gcc
           git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b gcc32 kernel/gcc32
           git clone --depth=1 https://github.com/etahamad/AnyKernel3 -b master kernel/AnyKernel
      
      - name: Building
        run: bash .github/workflows/build.sh
        env:
          CAM: OldCam
          token: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CI_CHANNEL_ID }}
